# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # JJGR: Change back to main from cicd
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      matrix:
        include: [{ msystem: MINGW64, arch: x86_64}]

    defaults:
      run:
        shell: cmd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up a minimal MSYS/MINGW environment
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: true
          install: base-devel git mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Collect dependencies
      - name: Collect dependencies
        run: msys2 -c './emacs-build.sh --debug --deps 2>&1'

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Runs a single command using the runners shell
      - name: Show we can write text
        run: msys2 -c './emacs-build.sh --help'

      # Clone emacs
      - name: Clone emacs
        run: msys2 -c './emacs-build.sh --clone 2>&1'

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Build only emacs
      - name: Build emacs
        run: msys2 -c './emacs-build.sh --build 2>&1'

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Pack only emacs
      - name: Pack emacs
        run: msys2 -c './emacs-build.sh --pack-emacs 2>&1'

      # Upload everything
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}-packages
          path: zips/*
