# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # JJGR: Change back to main from cicd
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      matrix:
        include: [{ msystem: MINGW64, arch: x86_64}]

    # Use the msys2.cmd wrapper to run all commands. This command invokes
    # a bash environment with the right msystem.
    defaults:
      run:
        shell: msys2 {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up a minimal MSYS/MINGW environment
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      # Runs a single command using the runners shell
      - name: Show we can write text
        run: echo Hello, world!

      # Build only emacs
      - name: Build emacs
        run: |
          mkdir zips
          ./emacs-build.sh --clone --deps --build --pack-emacs >zips/emacs-build.log 2>&1

      # Runs a complete build with all options
      #- name: Complete build
      #  run: ./emacs-build.sh --clone --deps --pdf-tools --hunspell --mu --isync --build --pack-emacs --pack-all >zips/emacs-build.log 2>&1

      # Upload everything
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}-packages
          path: zips/*
        
